version: "3"

services:
    node:
        build:
            context: node
        container_name: node
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
        networks:
            - node-network
        volumes:
            - ./node:/usr/src/app
        tty: true
        depends_on:
            - db
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks:
            - node-network
    nginx:
        build:
            context: nginx
        container_name: nginx
        networks:
            - node-network
        tty: true
        ports:
            - "8080:80"
networks:
    node-network:
        driver: bridge
